version: "3.3"

services:
  nextjs-app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args: # On ubuntu default docker gateway is 172.17.0.1. On Windows you need to use host.docker.internal so the app has access to it during build
        MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@172.17.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.5
    ports:
      - "3000:3000"
    networks:
      - tinacms-network
    environment:
      MONGODB_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@172.17.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.5"
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GITHUB_BRANCH: ${GITHUB_BRANCH}
      GITHUB_OWNER: ${GITHUB_OWNER}
      GITHUB_REPO: ${GITHUB_REPO}
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
      NEXTAUTH_URL: http://172.17.0.1:3000
      TINA_PUBLIC_IS_LOCAL: ${TINA_PUBLIC_IS_LOCAL}

networks:
  tinacms-network:
    external: true
