version: "3.3"
services:
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    container_name: tina-nextjs-app-mongodb
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
