#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
  echo "You can't push directly to master or main branch. Please create a pull request."
  exit 1
fi
